import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');
  // await page.getByPlaceholder('Username').click();
  // await page.getByPlaceholder('Username').fill('Admin');
  // await page.getByPlaceholder('Password').click();
  // await page.getByPlaceholder('Password').fill('admin123');
  // await page.getByRole('button', { name: 'Login' }).click();
  // await page.getByRole('button', { name: 'Leave List' }).click();
  // await page.locator('.oxd-date-input > .oxd-icon').first().click();
  // await page.getByText('2', { exact: true }).click();
  // await page.locator('div:nth-child(2) > .oxd-input-group > div:nth-child(2) > .oxd-date-wrapper > .oxd-date-input > .oxd-icon').click();
  // //await page.getByText('25').click();
  // await page.getByText('Select', { exact: true }).click();
  // await page.getByText('Cancelled').click();
  // await page.locator('div').filter({ hasText: /^Select$/ }).first().click();
  // await page.getByText('Taken').click();
  // await page.getByText('-- Select --').first().click();
  // await page.getByText('CAN - Personal').click();
  // await page.locator('div').filter({ hasText: /^-- Select --$/ }).nth(2).click();
  // await page.getByRole('option', { name: 'Development' }).click();
  // await page.getByPlaceholder('Type for hints...').click();
  // await page.getByPlaceholder('Type for hints...').click();
  // await page.getByRole('button', { name: 'Search' }).click();
  // await page.locator('div').filter({ hasText: /^Development$/ }).nth(2).click();
  // await page.getByRole('option', { name: 'Administration' }).click();
  // await expect(page.locator('div').filter({ hasText: /^Administration$/ }).nth(2)).toBeVisible();
  // await page.getByText('Emma Watson').click();
  // await expect(page.getByText('Emma Watson')).toBeVisible();
});